name: nsapp
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  intl: ^0.20.2
  google_fonts: ^6.2.1
  firebase_database: ^11.3.4
  cloud_firestore: ^5.6.5
  get: ^4.7.2
  dartz: ^0.10.1
  flutter_bloc:
  country_code_picker: ^3.2.0
  image_picker: ^1.1.2
  custom_radio_grouped_button: ^2.2.1
  location: ^8.0.0
  geocoding: ^3.0.0
  firebase_storage: ^12.4.4
  bloc_concurrency:
  skeletonizer: ^1.4.3
  google_sign_in: ^6.2.2
  uuid: ^4.5.1
  collection: ^1.19.1
  calendar_view: ^1.4.0
  http: ^1.3.0
  googleapis_auth: ^1.6.0
  firebase_messaging: ^15.2.4
  flutter_dotenv: ^5.2.1
  google_maps_flutter: ^2.11.0
  geoflutterfire_plus: ^0.0.32
  flutter_stripe: ^11.4.0
  flutter_rating: ^2.0.2
  rating_dialog: ^2.0.4
  flutter_map_math: ^0.2.1
  geolocator: ^13.0.4
  vector_math: ^2.1.4
  google_maps_directions: ^0.0.4
  local_auth: ^2.3.0
  internet_connection_checker_plus: ^2.7.1
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1
  google_maps_widget: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/
