// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1DdHVlpiVPxK0Y5JcAju4pSaVRcvADlE',
    appId: '1:681650672596:web:0ce17fc57330ae6941fc41',
    messagingSenderId: '681650672596',
    projectId: 'neighbor-service-app',
    authDomain: 'neighbor-service-app.firebaseapp.com',
    databaseURL: 'https://neighbor-service-app-default-rtdb.firebaseio.com',
    storageBucket: 'neighbor-service-app.firebasestorage.app',
    measurementId: 'G-HHWG6HK7HX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACCQQdSQl4HxPpmYZALC9py5cejq0hDOg',
    appId: '1:681650672596:android:79858960125159f141fc41',
    messagingSenderId: '681650672596',
    projectId: 'neighbor-service-app',
    databaseURL: 'https://neighbor-service-app-default-rtdb.firebaseio.com',
    storageBucket: 'neighbor-service-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXIu16vLotgDeUtLDKy6KZPiLsZ1wP5B0',
    appId: '1:681650672596:ios:a6aebe847add2f1f41fc41',
    messagingSenderId: '681650672596',
    projectId: 'neighbor-service-app',
    databaseURL: 'https://neighbor-service-app-default-rtdb.firebaseio.com',
    storageBucket: 'neighbor-service-app.firebasestorage.app',
    androidClientId: '681650672596-fbnhde0mclht9nfj5ocsauv7fsdga9bt.apps.googleusercontent.com',
    iosClientId: '681650672596-ddgbfrm58ajfs3keiat40b1bs5p54291.apps.googleusercontent.com',
    iosBundleId: 'com.neighborservice.nsapp',
  );
}
